name: Build and Deploy Angular App

on:
  push:
    branches: [ "main" ]  # Chỉ chạy khi push vào nhánh main
  pull_request:
    branches: [ "main" ]  # Hoặc khi có PR vào main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # Phiên bản phù hợp với Angular

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build -- --configuration=production
